Updated ruby version on jekyll.yml pipeline

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -17,7 +17,7 @@ jobs:
     - name: Set up Ruby
       uses: ruby/setup-ruby@v1
       with:
-        ruby-version: '2.7'
+        ruby-version: '3.1'
 
     - name: Install dependencies
       run: |
@@ -38,7 +38,7 @@ jobs:
       run: |
         gem install w3c_validators
         bundle exec jekyll build
-        vendor/bundle/ruby/2.7.0/bin/w3c_validators ./_site || echo "CSS linting errors detected. Check the report above."
+        vendor/bundle/ruby/3.1.0/bin/w3c_validators ./_site || echo "CSS linting errors detected. Check the report above."
 
     - name: Deploy to GitHub Pages
       if: always()
