Updated jekyll.yml pipeline to continue with errors

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -28,16 +28,20 @@ jobs:
       run: bundle exec jekyll build
 
     - name: HTML Validation
-      run: bundle exec htmlproofer ./_site --check-html
+      continue-on-error: true
+      run: |
+        gem install html-proofer
+        bundle exec htmlproofer ./_site --check-html || echo "HTML linting errors detected. Check the report above."
 
     - name: CSS Validation
+      continue-on-error: true
       run: |
         gem install w3c_validators
         bundle exec jekyll build
-        vendor/bundle/ruby/2.7.0/bin/w3c_validators ./_site
+        vendor/bundle/ruby/2.7.0/bin/w3c_validators ./_site || echo "CSS linting errors detected. Check the report above."
 
     - name: Deploy to GitHub Pages
-      if: success()
+      if: always()
       uses: peaceiris/actions-gh-pages@v3
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
