Link validation

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -27,6 +27,12 @@ jobs:
     - name: Build the site
       run: bundle exec jekyll build
 
+    - name: Link Validation
+      continue-on-error: true
+      run: |
+        gem install html-proofer
+        bundle exec htmlproofer ./_site || echo "Link validation errors detected. Check the report above."
+
     - name: Deploy to GitHub Pages
       if: always()
       uses: peaceiris/actions-gh-pages@v3
