Fixing HTML and CSS validation error on jekyll.yml

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -31,14 +31,14 @@ jobs:
       continue-on-error: true
       run: |
         gem install html-proofer
-        bundle exec htmlproofer ./_site --check-html || echo "HTML linting errors detected. Check the report above."
+        bundle exec htmlproofer ./_site --checks html || echo "HTML linting errors detected. Check the report above."
 
     - name: CSS Validation
       continue-on-error: true
       run: |
         gem install w3c_validators
         bundle exec jekyll build
-        vendor/bundle/ruby/3.1.0/bin/w3c_validators ./_site || echo "CSS linting errors detected. Check the report above."
+        bundle exec w3c_validators ./_site || echo "CSS linting errors detected. Check the report above."
 
     - name: Deploy to GitHub Pages
       if: always()
